version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - "127.0.0.1:${OPENAI_WEBGUI_PORT}:3002"
    environment:
      # 二选一
      OPENAI_API_KEY: "$OPENAI_API_KEY"
      # 二选一
      OPENAI_ACCESS_TOKEN: "$OPENAI_ACCESS_TOKEN"
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: "$OPENAI_API_BASE_URL"
      # API模型，可选，设置 OPENAI_API_KEY 时可用，https://platform.openai.com/docs/models
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-002
      OPENAI_API_MODEL: "$OPENAI_API_MODEL"
      # 反向代理，可选
      API_REVERSE_PROXY: "$OPENAI_API_REVERSE_PROXY"
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: "$OPENAI_AUTH_SECRET_KEY"
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: "$OPENAI_MAX_REQUEST_PER_HOUR"
      # 超时，单位毫秒，可选
      TIMEOUT_MS: "$OPENAI_TIMEOUT_MS"
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: "$OPENAI_SOCKS_PROXY_HOST"
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: "$OPENAI_SOCKS_PROXY_PORT"
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY: "$OPENAI_HTTPS_PROXY"