version: '3'

services:
  cfdns:
    image: classmatelin/cfdns:${CFDNS_VERSION}
    container_name: cfdns
    volumes:
      - ${CFDNS_CONF_DIR}:/usr/local/cfdns/conf
    environment:
      RUST_LOG: "$CFDNS_LOG_LEVEL"
    ports:
      - "${CFDNS_PORT}:53/udp"
    # 固定IP, zzdns中在设置上游DNS IP为这个IP.
    networks:
      dns:
        ipv4_address: 172.18.0.88
    hostname: "cfdns"

  # zzdns默认配置已设置上游其中一个上游DNS服务器为cfdns.可以快速返回cloudflare ip.
  zzdns:
    image: classmatelin/zzdns:${ZZDNS_VERSION}
    container_name: zzdns
    volumes:
      - ${ZZDNS_CONF_DIR}:/usr/local/zzdns/config
    environment:
      RUST_LOG: "$ZZDNS_LOG_LEVEL"
    ports:
      - "${ZZDNS_PORT}:53/udp"
    networks:
      dns:
        ipv4_address: 172.18.0.99
    hostname: "zzdns"

networks:
  dns:
    ipam:
      config:
      - subnet: 172.18.0.0/24