version: "3"
services:

  nas-tools:
    image: ${NASTOOL_IMAGE}
    ports:
      - "${NASTOOL_PORT}:3000"        # 默认的webui控制端口
    volumes:
      - "${NASTOOL_CONFIG_DIR}:/config" # 映射配置目录
      - "${NASTOOL_MEDIA_DIR}:/media"   # 映射媒体目录
    environment: 
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools

  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QB_VERSION}
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=${TIMEZONE}"
      - WEBUI_PORT=8080
    volumes:
      - ${QB_CONFIG_DIR}:/config
      - ${QB_DOWNLOAD_DIR}:/downloads
    ports:
      - "${QB_WEBUI_PORT}:8080"
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    network_mode: bridge
    hostname: qbittorrent

  emby:
    image: ${EMBY_IMAGE}
    container_name: emby
    privileged: true
    restart: unless-stopped
    ports:
      - "8096:8096"     # http
      - "8920:8920"     # https
      - "1900:1900/udp" # DLNA
      - "7359:7359/udp" # local network discovery
    environment:
      TZ: "$TIMEZONE"
      PUID: 0
      PGID: 0
      GIDLIST: 0
   
    volumes:
      - ${EMBY_CONFIG_DIR}:/config
      - ${EMBY_MEDIA_DIR}:/data

    network_mode: bridge
    hostname: emby